name: C Build
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build with Make
      run: make
      
    - name: Run the program (optional)
      run: ./company-analyzer
